/** Maps all accepted command strings (EN + ES) to canonical action names. */
const aliases: Record<string, string> = {
  '!create': 'create',
  '!crear': 'create',
  '!join': 'join',
  '!in': 'join',
  '!count': 'join',
  '!countmein': 'join',
  '!countonme': 'join',
  '!add': 'join',
  '!unir': 'join',
  '!unirme': 'join',
  '!unirse': 'join',
  '!apuntame': 'join',
  '!apuntar': 'join',
  '!apuntarme': 'join',
  '!waitlist': 'waitlist',
  '!onhold': 'waitlist',
  '!espera': 'waitlist',
  '!reserva': 'waitlist',
  '!leave': 'leave',
  '!out': 'leave',
  '!remove': 'leave',
  '!salir': 'leave',
  '!quitar': 'leave',
  '!status': 'status',
  '!info': 'status',
  '!estado': 'status',
  '!cancel': 'cancel',
  '!cancelar': 'cancel',
  '!anular': 'cancel',
  '!resize': 'resize',
  '!redimensionar': 'resize',
  '!plazas': 'resize',
  '!rename': 'rename',
  '!renombrar': 'rename',
  '!nombre': 'rename',
  '!lang': 'lang',
  '!idioma': 'lang',
  '!invite': 'invite',
  '!invitar': 'invite',
  '!help': 'help',
  '!ayuda': 'help',
  '!groups': 'groups',
  '!grupos': 'groups',
  '!draw': 'groups',
  '!sorteo': 'groups',
};

export function resolveCommand(raw: string): string | undefined {
  return aliases[raw];
}
